# Generated by Django 3.2.13 on 2022-05-18 21:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('information', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE,
                                           to='provider.provider', to_field='name')),
            ],
        ),
    ]
