# Generated by Django 3.2.13 on 2022-05-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polygon',
            old_name='name',
            new_name='provider',
        ),
    ]
