# Generated by Django 3.2.13 on 2022-05-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('email', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('language', models.CharField(max_length=30, null=True)),
                ('currency', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
