# Generated by Django 3.2.13 on 2022-05-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20220517_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='currency',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='language',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
